{
 "title": "Docker Monitoring",
 "tags": [ "docker" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "cadvisor" },
   { "name": "node_job", "label": "Node Job", "query": "node" },
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "label_values({exported_job=\"$job\"},site)"
    }
   },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values({exported_job=\"$job\", site=\"$site\"},exported_instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Host Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{exported_instance=\"$node:9100\", exported_job=\"$node_job\", site=\"$site\"} - node_boot_time_seconds{exported_instance=\"$node:9100\", site=\"$site\", exported_job=\"$node_job\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "machine_cpu_cores{exported_instance=\"$node:8080\",site=\"$site\",exported_job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{exported_instance=\"$node:9100\",site=\"$site\",exported_job=\"$node_job\"}"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{exported_instance=\"$node:9100\",site=\"$site\",exported_job=\"$node_job\"}) - sum(node_memory_MemFree_bytes{exported_instance=\"$node:9100\",site=\"$site\",exported_job=\"$node_job\"}+node_memory_Buffers_bytes{exported_instance=\"$node:9100\",site=\"$site\",exported_job=\"$node_job\"}+node_memory_Cached_bytes{exported_instance=\"$node:9100\",site=\"$site\",exported_job=\"$node_job\"})"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{exported_instance=\"$node:9100\",site=\"$site\",exported_job=\"$node_job\"}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{exported_instance=\"$node:9100\",site=\"$site\",exported_job=\"$node_job\",mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "Used Storage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{image!=\"\", exported_instance=\"$node:8080\",site=\"$site\",exported_job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{image!=\"\", exported_name=~\".+\",exported_instance=\"$node:8080\",site=\"$site\",exported_job=\"$job\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\", exported_instance=\"$node:8080\",site=\"$site\",exported_job=\"$job\"}[1m])) / count(node_cpu_seconds_total{mode=\"user\", exported_instance=\"$node:9100\",site=\"$site\",exported_job=\"$node_job\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory Load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes{exported_instance=\"$node:9100\",site=\"$site\",exported_job=\"$node_job\"}) - sum(node_memory_MemFree_bytes{exported_instance=\"$node:9100\",site=\"$site\",exported_job=\"$node_job\"}+node_memory_Buffers_bytes{exported_instance=\"$node:9100\",site=\"$site\",exported_job=\"$node_job\"}+node_memory_Cached_bytes{exported_instance=\"$node:9100\",site=\"$site\",exported_job=\"$node_job\"}) ) / sum(node_memory_MemTotal_bytes{exported_instance=\"$node:9100\",site=\"$site\",exported_job=\"$node_job\"}) * 100"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{exported_instance=\"$node:9100\",site=\"$site\",exported_job=\"$node_job\"} - node_memory_SwapFree_bytes{exported_instance=\"$node:9100\",site=\"$site\",exported_job=\"$node_job\"}) / (node_memory_SwapTotal_bytes{exported_instance=\"$node:9100\",site=\"$site\",exported_job=\"$node_job\"} )) * 100"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{exported_instance=\"$node:9100\",site=\"$site\",exported_job=\"$node_job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{exported_instance=\"$node:9100\",site=\"$site\",exported_job=\"$node_job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  { "title": "Container Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Limit Reached",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_spec_cpu_quota{exported_name=~\".+\", image!=\"\", exported_instance=\"$node:8080\",site=\"$site\",exported_job=\"$job\"}) / 100000"
    }
   ]
  },
  {
   "title": "Usage CPU",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{exported_name=~\".+\", image!=\"\", exported_instance=\"$node:8080\",site=\"$site\",exported_job=\"$job\"}[$__rate_interval])) by (exported_name) * 100",
     "legendFormat": "{{exported_name}}"
    }
   ]
  },
  {
   "title": "Limit CPU",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(container_spec_cpu_quota{exported_name=~\".+\",exported_instance=\"$node:8080\",site=\"$site\",exported_job=\"$job\"}) by (exported_name) / 100000",
     "legendFormat": "{{exported_name}}"
    }
   ]
  },
  {
   "title": "Memory Limit Reached",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_spec_memory_limit_bytes{exported_name=~\".+\",image!=\"\", exported_instance=\"$node:8080\",site=\"$site\",exported_job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Usage memory",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{exported_name=~\".+\",exported_instance=\"$node:8080\",site=\"$site\",exported_job=\"$job\"}",
     "legendFormat": "{{exported_name}}"
    }
   ]
  },
  {
   "title": "Limit memory",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_spec_memory_limit_bytes{exported_name=~\".+\",exported_instance=\"$node:8080\",site=\"$site\",exported_job=\"$job\"}) by (exported_name) ",
     "legendFormat": "{{exported_name}}"
    }
   ]
  },
  {
   "title": "Remaining memory",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum((100 - (container_spec_memory_limit_bytes{exported_name=~\".+\", image!=\"\", exported_instance=\"$node:8080\",site=\"$site\",exported_job=\"$job\"} - container_memory_usage_bytes{exported_name=~\".+\", image!=\"\", exported_instance=\"$node:8080\",site=\"$site\",exported_job=\"$job\"})  * 100 / container_spec_memory_limit_bytes{exported_name=~\".+\", image!=\"\", exported_instance=\"$node:8080\",site=\"$site\",exported_job=\"$job\"}) ) by (exported_name) ",
     "legendFormat": "{{exported_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{exported_name=~\".+\",exported_instance=\"$node:8080\",site=\"$site\",exported_job=\"$job\"}[$__rate_interval])) by (exported_name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Swap per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_swap{exported_name=~\".+\", image!=\"\", exported_instance=\"$node:8080\",site=\"$site\",exported_job=\"$job\"}) by (exported_name)",
     "legendFormat": "{{exported_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{exported_name=~\".+\", image!=\"\", exported_instance=\"$node:8080\",site=\"$site\",exported_job=\"$job\"}) by (exported_name)",
     "legendFormat": "{{exported_name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{exported_name=~\".+\", image!=\"\", exported_instance=\"$node:8080\",site=\"$site\",exported_job=\"$job\"}[$__rate_interval])) by (exported_name)",
     "legendFormat": "{{exported_name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{exported_name=~\".+\", image!=\"\", exported_instance=\"$node:8080\",site=\"$site\",exported_job=\"$job\"}[$__rate_interval])) by (exported_name)",
     "legendFormat": "{{exported_name}}"
    }
   ]
  }
 ]
}