{
 "title": "Proxmox Monitoring",
 "description": "Proxmox Virtual Environment",
 "tags": [ "proxmox" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "pve" },
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "label_values({exported_job=\"$job\"},site)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values({exported_job=\"$job\", site=\"$site\"},cluster)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values({exported_job=\"$job\", site=\"$site\", cluster=\"$cluster\"},exported_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_cpu_usage_ratio{site=\"$site\", cluster=\"$cluster\", exported_instance=\"$node\", exported_job=\"$job\"} / pve_cpu_usage_limit and on(id) pve_node_info"
    }
   ]
  },
  {
   "title": "Current memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_memory_usage_bytes{site=\"$site\", cluster=\"$cluster\", exported_instance=\"$node\",exported_job=\"$job\"} / pve_memory_size_bytes and on(id) pve_node_info"
    }
   ]
  },
  {
   "title": "Storage usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pve_disk_usage_bytes{site=\"$site\", cluster=\"$cluster\", exported_instance=\"$node\",exported_job=\"$job\", id=~\"storage/.+\"} / pve_disk_size_bytes * on (id, instance) group_left(storage) pve_storage_info",
     "legendFormat": "{{storage}}"
    }
   ]
  },
  {
   "title": "Space allocation",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_disk_size_bytes{site=\"$site\", cluster=\"$cluster\", exported_instance=\"$node\",exported_job=\"$job\", id=~\"storage/.+\"} * on (id, instance) group_left(storage) pve_storage_info",
     "legendFormat": "{{storage}}"
    }
   ]
  },
  {
   "title": "Total VMs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (id) (pve_guest_info{site=\"$site\", cluster=\"$cluster\", exported_instance=\"$node\",exported_job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Running VMs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (pve_guest_info{site=\"$site\", cluster=\"$cluster\", exported_instance=\"$node\",exported_job=\"$job\"})"
    },
    {
     "expr": "sum by (id) (pve_up{site=\"$site\", cluster=\"$cluster\", exported_instance=\"$node\",exported_job=\"$job\"} and on (id, instance) pve_guest_info)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_cpu_usage_limit{site=\"$site\", cluster=\"$cluster\", exported_instance=\"$node\",exported_job=\"$job\"} and on(id) pve_node_info",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_memory_usage_bytes{site=\"$site\", cluster=\"$cluster\", exported_instance=\"$node\",exported_job=\"$job\"} and on(id) pve_node_info",
     "legendFormat": "__auto"
    },
    {
     "expr": "pve_memory_size_bytes{site=\"$site\", cluster=\"$cluster\", exported_instance=\"$node\",exported_job=\"$job\"} and on(id) pve_node_info",
     "legendFormat": "__auto"
    },
    {
     "expr": "pve_memory_size_bytes{site=\"$site\", cluster=\"$cluster\", exported_instance=\"$node\",exported_job=\"$job\"} and on(id) pve_node_info",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU history",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "pve_cpu_usage_ratio{site=\"$site\", cluster=\"$cluster\", exported_instance=\"$node\",exported_job=\"$job\"} and on(id) pve_node_info",
     "legendFormat": "__auto"
    },
    {
     "expr": "pve_cpu_usage_limit{site=\"$site\", cluster=\"$cluster\", exported_instance=\"$node\",exported_job=\"$job\"} and on(id) pve_node_info",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory history",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pve_memory_usage_bytes{site=\"$site\", cluster=\"$cluster\", exported_instance=\"$node\",exported_job=\"$job\"} and on(id) pve_node_info",
     "legendFormat": "__auto"
    },
    {
     "expr": "pve_memory_size_bytes{site=\"$site\", cluster=\"$cluster\", exported_instance=\"$node\",exported_job=\"$job\"} and on(id) pve_node_info",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource allocation summary",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (id, name, type) (pve_guest_info{site=\"$site\", cluster=\"$cluster\", exported_instance=\"$node\",exported_job=\"$job\"})"
    },
    {
     "expr": "sum by (id) (pve_up{site=\"$site\", cluster=\"$cluster\", exported_instance=\"$node\",exported_job=\"$job\"} and on (id, instance) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_cpu_usage_limit{exported_site=\"$site\", cluster=\"$cluster\", exported_instance=\"$node\",exported_job=\"$job\"} and on (id, instance) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_memory_size_bytes{site=\"$site\", cluster=\"$cluster\", exported_instance=\"$node\",exported_job=\"$job\"} and on (id, instance) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_memory_usage_bytes{site=\"$site\", cluster=\"$cluster\", exported_instance=\"$node\",exported_job=\"$job\",template!=\"1\"} / pve_memory_size_bytes and on (id, instance) pve_guest_info and on (id) pve_up==1)"
    },
    {
     "expr": "sum by (id) (pve_disk_size_bytes{site=\"$site\", cluster=\"$cluster\", exported_instance=\"$node\",exported_job=\"$job\"} and on (id, instance) pve_guest_info)"
    },
    {
     "expr": "sum by (id) (pve_disk_usage_bytes{site=\"$site\", cluster=\"$cluster\", exported_instance=\"$node\",exported_job=\"$job\"} / pve_disk_size_bytes and on (id, instance) pve_guest_info{type=\"lxc\"})"
    }
   ]
  },
  {
   "title": "Guests CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "((pve_cpu_usage_ratio{site=\"$site\", cluster=\"$cluster\", exported_instance=\"$node\",exported_job=\"$job\"} / pve_cpu_usage_limit) * on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
     "legendFormat": "{{name}} ({{type}})"
    }
   ]
  },
  {
   "title": "Guests memory usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(pve_memory_usage_bytes{site=\"$site\", cluster=\"$cluster\", exported_instance=\"$node\",exported_job=\"$job\"} / pve_memory_size_bytes * on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
     "legendFormat": "{{name}} ({{type}})"
    }
   ]
  },
  {
   "title": "Network IO/s",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(rate(pve_network_receive_bytes{site=\"$site\", cluster=\"$cluster\", exported_instance=\"$node\",exported_job=\"$job\"}[5m]) * on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
     "legendFormat": "{{name}} RECV ({{type}})"
    },
    {
     "expr": "(rate(pve_network_transmit_bytes{site=\"$site\", cluster=\"$cluster\", exported_instance=\"$node\",exported_job=\"$job\"}[5m])* on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
     "legendFormat": "{{name}} SEND ({{type}})"
    }
   ]
  },
  {
   "title": "Disk IO/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "((rate(pve_disk_write_bytes{site=\"$site\", cluster=\"$cluster\", exported_instance=\"$node\",exported_job=\"$job\"}[5m]) + rate(pve_disk_read_bytes[5m])) * on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
     "legendFormat": "{{name}} ({{type}})"
    }
   ]
  },
  {
   "title": "LXC guests Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pve_disk_usage_bytes{site=\"$site\", cluster=\"$cluster\", exported_instance=\"$node\",exported_job=\"$job\"} / pve_disk_size_bytes{site=\"$site\", cluster=\"$cluster\", exported_instance=\"$node\",exported_job=\"$job\"} * on (id, instance) group_left(name, type) pve_guest_info{type=\"lxc\"}",
     "legendFormat": "{{name}} ({{type}})"
    }
   ]
  }
 ]
}