{
 "title": "UPS Monitoring",
 "description": "DevOpsLab UPS Monitoring",
 "tags": [ "ups" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "nut" },
   { "name": "smoothing_interval", "label": "Smoothing", "query": "1m,5m,15m,1h,1d,1w" },
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "label_values({exported_job=\"$job\"},site)"
    }
   },
   {
    "name": "ups",
    "label": "UPS",
    "query": {
     "query": "label_values({exported_job=\"$job\", site=\"$site\"},ups)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_status{exported_job=\"$job\", site=\"$site\", ups=\"$ups\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_input_voltage_volts{exported_job=\"$job\", site=\"$site\", ups=\"$ups\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_load{exported_job=\"$job\", site=\"$site\", ups=\"$ups\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Charge",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_battery_charge{exported_job=\"$job\", site=\"$site\", ups=\"$ups\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_battery_runtime_seconds{exported_job=\"$job\", site=\"$site\", ups=\"$ups\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "nut_ups_info{exported_job=\"$job\", site=\"$site\", ups=\"$ups\"}"
    }
   ]
  },
  {
   "title": "Beeper Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_beeper_status{exported_job=\"$job\", site=\"$site\", ups=\"$ups\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Battery Charge [$smoothing_interval]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * avg_over_time(nut_battery_charge{exported_job=\"$job\", site=\"$site\", ups=\"$ups\"}[$smoothing_interval])",
     "legendFormat": "{{ups}} Current"
    },
    {
     "expr": "100 * avg_over_time(nut_battery_charge_low{exported_job=\"$job\", site=\"$site\", ups=\"$ups\"}[$smoothing_interval])",
     "legendFormat": "{{ups}} Low"
    }
   ]
  },
  {
   "title": "Runtime [$smoothing_interval]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(nut_battery_runtime_seconds{exported_job=\"$job\", site=\"$site\", ups=\"$ups\"}[$smoothing_interval])",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Input Voltage [$smoothing_interval]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "avg_over_time(nut_input_voltage_volts{exported_job=\"$job\", site=\"$site\", ups=\"$ups\"}[$smoothing_interval])",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Load [$smoothing_interval]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(nut_load{exported_job=\"$job\", site=\"$site\", ups=\"$ups\"}[$smoothing_interval])",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Input Frequency [$smoothing_interval]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "avg_over_time(nut_input_frequency_hertz{exported_job=\"$job\", site=\"$site\", ups=\"$ups\"}[$smoothing_interval])",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Status Change",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_status{flag=~\"OL|OB|LB\", exported_job=\"$job\", site=\"$site\", ups=\"$ups\"}",
     "legendFormat": "{{flag}}"
    }
   ]
  },
  {
   "title": "Output Voltage [$smoothing_interval]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "avg_over_time(nut_output_voltage_volts{exported_job=\"$job\", site=\"$site\", ups=\"$ups\"}[$smoothing_interval])",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Output Frequency [$smoothing_interval]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "avg_over_time(nut_output_frequency_hertz{exported_job=\"$job\", site=\"$site\", ups=\"$ups\"}[$smoothing_interval])",
     "legendFormat": "{{ups}}"
    }
   ]
  }
 ]
}